[theme]
base = "light"
primaryColor = "#00C86F"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
